### ISSUE TITLE
Error: length of query MSF longer than expected PANTHER alignment length

### ISSUE THREAD

**Issue by cooketho** [ebi-pf-team/treegrafter#3]
I'm seeing a similar error to the one reported here:

https://github.com/pantherdb/TreeGrafter/issues/7

When I run hmmsearch on the same sequence as in that post, using PANTHER16.0

```
>Cyanophora_paradoxa_CPAR027107_Apc11
QKTLTILAKDRNYKVEDFKAAGAIAKTRLDQQREPCSCKVAASDAHPCVRRVLFLNLSAA
VGAREPRLGARRAPALRSMKVKIVWHAVASWTWNVDDEACGICRNAYDGCCPDCKTPGDD
CPLWGECRHAFHLHCILKWVNSQQEGKQHCPMCRRDWKFRSSD
```

and then run treegrafter on the results, I get the following error:

```
Error: length of query MSF longer than expected PANTHER alignment length: expected 102, got 89
```

I'm using:
treegrafter commit 40cff5a633d61958910d06a84e9cf277a5547e66
HMMER 3.3.2
PANTHER16.0_data

**Comment by cooketho** [comment]
It seems the block of code triggering the error is in treegrafter.py:

```
    # error check (is this required?)
    if len(querymsf) != pthr_align_length:
        # then something is wrong
        sys.stderr.write("Error: length of query MSF longer than expected "
                         "PANTHER alignment length: expected {}, "
                         "got {}.".format(pthr_align_length, len(querymsf)))
        sys.exit(1)
```
Now the code above, combined with the error reporting, shows that:
pthr_align_length = 102
len(query_msf) = 89

And by eye, the length of the alignment, including gaps, is 89, and I see from PANTHER16.0_data/Tree_MSF/PTHR11210.AN.fasta that the length of the PANTHER alignment is 102. So the values of those variables makes sense.

It's the stderr expression that doesn't make sense, because the length of the query is not actually longer than the panther alignment--the variable order in the expression is swapped. But even if it were fixed (and also "!=" replaced with "<"), why is this error check necessary? Don't we expect to see query alignments that are shorter than the panther alignment all the time?

Anyway, thank you for re-implementing this in Python! It's a big help to me because the other one is in perl and I forgot all I used to know about perl.

**Comment by tgrego** [comment]
You're right that this is related to the original treegrafter issue you linked.
We found that that issue (usually) happens when we go several domain hits from hmmer. When building the query_msf the original treegrafter uses the hmmer alignments from all significant domain hits and that causes the query_msa to be too long, triggering the error.

Now the query_msa needs to be the same size as the pthr_align_length, so the check is correct but the error message is not great as it points to what we expected to see triggering the error. If smaller than the pthr_align_length I expected the query_msa to be padded to the right size, so I need to double check that.

Thanks for reporting!
